const Discord = require("discord.js");
const IPE = new Discord.EmbedBuilder()
    .setTitle("Invalid Permissions!")
    .setDescription("You are not authorized to use this command!")
    .setColor("#f09999")
    .setTimestamp()
const NPE = new Discord.EmbedBuilder()
    .setTitle("Invalid Permissions!")
    .setDescription("I'm not authorised to do the actions in the command!")
    .setColor("#f09999")
    .setTimestamp()
const IWC = new Discord.EmbedBuilder()
    .setTitle("Invalid Warning Case!")
    .setColor("#f09999")
    .setDescription("The warning case you provided is invalid!")
    .setTimestamp()
const IWCDB = new Discord.EmbedBuilder()
    .setTitle("Invalid Warning Case!")
    .setColor("#f09999")
    .setDescription("The warning case you provided cannot be founded in the bot Database!")
    .setTimestamp()
const IUSPPRE = new Discord.EmbedBuilder()
    .setTitle("Invalid prefix!")
    .setDescription("The prefix you provided contains a space!")
    .setColor("#f09999")
    .setTimestamp()
const STB = new Discord.EmbedBuilder()
    .setTitle("Invalid Usage!")
    .setDescription("You are not allowed to timeout yourself nor any bots!")
    .setColor("#f09999")
    .setTimestamp()
const ITD = new Discord.EmbedBuilder()
    .setTitle("Invalid Timeout Duration!")
    .setDescription("Timeout Duration cannot be less than 5s or more then 28 days!")
    .setColor("#f09999")
    .setTimestamp()
const NCMD = new Discord.EmbedBuilder()
    .setTitle("Invalid Command Usage!")
    .setDescription(`> **Usage** \n.blacklist <guild/user> <guildId/userId> reason`)
    .setColor("#f09999")
    .setTimestamp()
const NRE = new Discord.EmbedBuilder()
    .setTitle("Invalid Reason!")
    .setDescription("Please make sure you put a valid reason!")
    .setColor("#f09999")
    .setTimestamp()
const BLG = new Discord.EmbedBuilder()
    .setTitle("Server Blacklisted!")
    .setDescription(`> This server has been blacklisted by TeaFluff's moderators/developers!\n> Please use the command </appeal-server:1100779102132256789> to send an appeal!`)
    .setTimestamp()
    .setColor("#f09999")
const BLU = new Discord.EmbedBuilder()
    .setTitle("User Blacklisted!")
    .setDescription(`> You have been blacklisted by TeaFluff's moderators/developers!\n> Please use the command `)
    .setTimestamp()
    .setColor("#f09999")
const INS = new Discord.EmbedBuilder()
    .setTitle("Server not found!")
    .setDescription("The server name that you provided was not found in the bot server list!")
    .setTimestamp()
    .setColor("#f09999")
const MSS = new Discord.EmbedBuilder()
    .setTitle("Your Appeal have been submitted!")
    .setDescription("Your appeal has been submitted successfully! Please wait patiently for an moderator to accept/deny your appeal!")
    .setColor("#a8f1b0")
    .setTimestamp()
const NCH = new Discord.EmbedBuilder()
    .setTitle("Invalid Command Usage!")
    .setDescription("> Usage \n.embed <channel>")
    .setColor("#f09999")
    .setTimestamp()
module.exports = { IPE, NPE, IWC, IWCDB, IUSPPRE, STB, ITD, NCMD, NRE, BLU, BLG, INS, MSS, NCH }
